-- SUPERSEDED — do not run this against any environment.
--
-- DeletedTickets is a table in the shared `Patchlab` database, which this repo
-- (Dapper-only, no EF Core, no migrations) does not own the schema for. Schema
-- for the shared database — including this table — is owned by
-- PatchlabWhatsAppBot via EF Core migrations (see its AddResolvedAtToTickets
-- migration for the pattern this table now follows: AddDeletedTicketsTable,
-- or equivalent).
--
-- This script originally created DeletedTickets by hand against local dev
-- only. It had no auto-apply path, so it never reached production, and the
-- hard-delete feature shipped broken there (SqlException: Invalid object name
-- 'DeletedTickets'). Kept here only for historical reference to the column
-- layout this repo's DELETE /api/Tickets/{id} logic expects; the bot-side
-- migration is the actual source of truth for this table's schema going
-- forward.
